COMPONENT_ADD_INCLUDEDIRS := src
COMPONENT_SRCDIRS := src
COMPONENT_REQUIRES := ESPressio_Timing

CXXFLAGS += -DESPRESSIO_ESPNOW
CXXFLAGS += -DESPRESSIO_ESPNOW_VERSION_MAJOR=0
CXXFLAGS += -DESPRESSIO_ESPNOW_VERSION_MINOR=6
CXXFLAGS += -DESPRESSIO_ESPNOW_VERSION_PATCH=0
CXXFLAGS += -DESPRESSIO_ESPNOW_VERSION_STRING=\"0.6.0\"
